common: &common
  app_name: Parkerhill
  app_url: http://www.parkerhill.com
  host: parkerhill.com
  admin_email: admin@parkerhill.com
  company_name: Parkerhill Tech
  contact_email: info@parkerhill.com
  
development:
  domain: localhost:3000
  <<: *common

test:
  domain: test.host
  <<: *common

production:
  domain: example.com
  <<: *common

